"""add DisponibilidadDocente table

Revision ID: 4234052a99d4
Revises: 775379b80429
Create Date: 2025-05-15 04:27:27.347469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4234052a99d4'
down_revision: Union[str, None] = '775379b80429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asignaturasdocente')
    op.drop_constraint('DisponibilidadDocente_id_asignatura_fkey', 'DisponibilidadDocente', type_='foreignkey')
    op.drop_column('DisponibilidadDocente', 'id_asignatura')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DisponibilidadDocente', sa.Column('id_asignatura', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('DisponibilidadDocente_id_asignatura_fkey', 'DisponibilidadDocente', 'Asignaturas', ['id_asignatura'], ['id_asignatura'])
    op.create_table('asignaturasdocente',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_profesor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_asignatura', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_asignatura'], ['Asignaturas.id_asignatura'], name='asignaturasdocente_id_asignatura_fkey'),
    sa.ForeignKeyConstraint(['id_profesor'], ['Usuarios.id_usuario'], name='asignaturasdocente_id_profesor_fkey'),
    sa.PrimaryKeyConstraint('id', name='asignaturasdocente_pkey')
    )
    # ### end Alembic commands ###
