"""add notificaciones table

Revision ID: 6fcb3915639e
Revises: 6caac54f9e38
Create Date: 2025-06-03 21:11:05.540042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fcb3915639e'
down_revision: Union[str, None] = '6caac54f9e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Notificaciones',
    sa.Column('id_notificacion', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_profesor', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['Usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_profesor'], ['Usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_index(op.f('ix_Notificaciones_id_notificacion'), 'Notificaciones', ['id_notificacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Notificaciones_id_notificacion'), table_name='Notificaciones')
    op.drop_table('Notificaciones')
    # ### end Alembic commands ###
