"""add all main tables without chat

Revision ID: 775379b80429
Revises: 662008bae4cc
Create Date: 2025-05-14 14:56:04.124941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775379b80429'
down_revision: Union[str, None] = '662008bae4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Asignaturas',
    sa.Column('id_asignatura', sa.Integer(), nullable=False),
    sa.Column('nombre_asignatura', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_asignatura'),
    sa.UniqueConstraint('nombre_asignatura')
    )
    op.create_index(op.f('ix_Asignaturas_id_asignatura'), 'Asignaturas', ['id_asignatura'], unique=False)
    op.create_table('DisponibilidadDocente',
    sa.Column('id_disponibilidad', sa.Integer(), nullable=False),
    sa.Column('id_profesor', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_hora_fin', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_profesor'], ['Usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_disponibilidad')
    )
    op.create_index(op.f('ix_DisponibilidadDocente_id_disponibilidad'), 'DisponibilidadDocente', ['id_disponibilidad'], unique=False)
    op.create_table('Tutorias',
    sa.Column('id_tutoria', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_profesor', sa.Integer(), nullable=False),
    sa.Column('id_asignatura', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_hora_fin', sa.DateTime(), nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_confirmacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_cancelacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_asignatura'], ['Asignaturas.id_asignatura'], ),
    sa.ForeignKeyConstraint(['id_profesor'], ['Usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_estudiante'], ['Usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_tutoria')
    )
    op.create_index(op.f('ix_Tutorias_id_tutoria'), 'Tutorias', ['id_tutoria'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tutorias_id_tutoria'), table_name='Tutorias')
    op.drop_table('Tutorias')
    op.drop_index(op.f('ix_DisponibilidadDocente_id_disponibilidad'), table_name='DisponibilidadDocente')
    op.drop_table('DisponibilidadDocente')
    op.drop_index(op.f('ix_Asignaturas_id_asignatura'), table_name='Asignaturas')
    op.drop_table('Asignaturas')
    # ### end Alembic commands ###
