"""migracion

Revision ID: 7d6015153df3
Revises: da97cf9bb513
Create Date: 2025-06-03 20:40:07.609476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d6015153df3'
down_revision: Union[str, None] = 'da97cf9bb513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProfesorAsignatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_profesor', sa.Integer(), nullable=False),
    sa.Column('id_asignatura', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_asignatura'], ['Asignaturas.id_asignatura'], ),
    sa.ForeignKeyConstraint(['id_profesor'], ['Usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_profesor', 'id_asignatura', name='_profesor_asignatura_uc')
    )
    op.create_index(op.f('ix_ProfesorAsignatura_id'), 'ProfesorAsignatura', ['id'], unique=False)
    op.alter_column('Tutorias', 'fecha_solicitud',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tutorias', 'fecha_solicitud',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ProfesorAsignatura_id'), table_name='ProfesorAsignatura')
    op.drop_table('ProfesorAsignatura')
    # ### end Alembic commands ###
