"""arreglos

Revision ID: da97cf9bb513
Revises: 4234052a99d4
Create Date: 2025-05-15 04:57:16.505336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da97cf9bb513'
down_revision: Union[str, None] = '4234052a99d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DisponibilidadDocente',
    sa.Column('id_disponibilidad', sa.Integer(), nullable=False),
    sa.Column('id_profesor', sa.Integer(), nullable=False),
    sa.Column('id_asignatura', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=10), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_asignatura'], ['Asignaturas.id_asignatura'], ),
    sa.ForeignKeyConstraint(['id_profesor'], ['Usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_disponibilidad')
    )
    op.create_index(op.f('ix_DisponibilidadDocente_id_disponibilidad'), 'DisponibilidadDocente', ['id_disponibilidad'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_DisponibilidadDocente_id_disponibilidad'), table_name='DisponibilidadDocente')
    op.drop_table('DisponibilidadDocente')
    # ### end Alembic commands ###
